### ISSUE TITLE
Pilot Project for Teacher to use TeachOSM

### ISSUE THREAD

**Issue by jlouellette** [osmlab/teachosm#71]
Recruit a teacher to pilot a project using TeachOSM to get feedback on the website and help create a lesson plan for other teachers to use.

**Comment by geomantic** [comment]
Shawn Goulet @sgoulet might be a good resource for this as he's been working with a high school teacher in Mass. to implement OSM in the curriculum.

**Comment by sgoulet** [comment]
Would love to help out.  I will be giving a talk on our TeachOSM work on Cape Cod at SOTMUS (http://stateofthemap.us/gis-smorgasbord/) ... was hoping to have one or both teachers with me, but unfortunately SOTMUS conflicts with both their schedules.  One - graduation, the other will be grading AP exams with The College Board.

**Comment by sgoulet** [comment]
Here's my *in development* documentation of the work with 2 high school AP Geography programs here on Cape Cod: https://docs.google.com/document/d/1G7UapqLwTByYYmtOqwt3XOj4y8Z9Q7lXM2o9cWH2bT8/edit?usp=sharing ... please feel free to provide any feedback to me shawn[dot]goulet[at]gmail[dot]com on the email.

**Comment by sgoulet** [comment]
I need to start doing this: @geomantic & @jlouellette RE above 2 comments.

**Comment by geomantic** [comment]
@sgoulet Any teacher feedback on TeachOSM? Or, not yet?

**Comment by sgoulet** [comment]
Hey @geomantic, hope all is well.  Unfortunately I haven't been able to work with any classes thus far this year.  Work hasn't allowed me to commit time during the workday as of yet.  So nothing yet, but hopefully at some point...I will let you know.

**Comment by TomM4** [comment]
I am going to the PA Geographic Alliance Education Meeting today.  I am going to discuss this project.  We are also going to complete a workshop for AP Human Geography teachers in June.  I am not sure if they will have laptops or internet.  However I am thinking of introducing this project to them and gather some volunteers.  

One thing I am thinking is I think we need to create maybe some simple PowerPoints or something on the entities.  For example, Facilities of Workshop have these attributes, etc.  I can start that (if everyone thinks it is worthwhile).  Here was my plan (using the OSM Course Sections) build my part of the workshop on Weeks 1 (Geography) and 2 (Population and Migration).  I could build the PowerPoints and share them with this group and you could give my thumbs up and down.

Finally I am going to examine FieldPapers again (it has been awhile). 

Just my two cents

**Comment by geomantic** [comment]
@TomM4 this is great. I've been giving workshops to APHG teachers, as well. Let's compare notes. I've got quite a few observations I can share.

**Comment by TomM4** [comment]
Excellent.  Please share them and when I have something ready I will share with the group

**Comment by shawnmgoulet** [comment]
@TomM4 @geomantic this is **great**.  With this project, I think it's important to constantly keep the scale-ability in mind.  Some instructors might have 1 hr a week, others a month, others a quarter, some might do it as a sprint at the end of the year.

In my mind, I've always seen a set of instructor implementation scenarios for them to choose from given their situation.  My take is that making it easy for them to pick up & go is the :key:.

**Comment by TomM4** [comment]
I just talked to @shawnmgoulet I was thinking (and it may be off base - my 7 year old tells me I am wrong all the time) that if we built "a modular course" it might be helpful to teachers.  For example, there are great how to videos on building features in OSM. I think we need to pull the best of them (so that teachers can watch them).  We would build a module on the features of OSM.  What is a node? What is line, etc.?  So either we or the teacher could have those materials in the beginning of her course.

Then build a module based on the topics for APHG.  So build one on Population and Migration (discuss hospitals, education facilities, etc.) with discussion the attributes, etc.  Then build one on Agriculture, etc.  This way a teacher may not use OSM throughout their course but maybe they said I am going to use OSM to better explain this topic, so they use that module.

We would hope that students would also contribute locally, etc.  Again just my two cents.  There might be some grants we can tap into via AAG or NGS.  The chair of the committee that I will meet is a AP HG guru so I will ask her opinion, etc.  and then report back to the group

**Comment by geomantic** [comment]
@shawnmgoulet @TomM4 We're circling around the same ideas, particularly with regard to show how open mapping fits into the lessons being taught. Specifically, the implementation scenarios and topic-based modules you both mention. I've been referring to that as the 'content'.

The other piece is being able to help teachers introduce open mapping in the class, i.e. the logistics of putting on a classroom mapathon. In addition to content, teachers need help with OSM account management, training materials for youth, in-school support for hardware/software (browsers, OS, etc), Tasking Mgr training, etc. In short, a lot of support.

I've put together some thoughts already, will post them up here somewhere, probably in /files .

**Comment by geomantic** [comment]
@shawnmgoulet @tomM4 Closing this issue and sending everyone over to https://github.com/shawnmgoulet/teachosm-for-high-school because it fulfills the intent of this issue.
